<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<?php 
if(!Mage::helper('marketplace')->checkMarketplaceKey()){ 
 $model = Mage::getModel('customer/customer')->getCollection()->addAttributeToFilter('customerstatus',1);       
    $id = array();
       if ($model->getSize() > 0) {
           foreach ($model as $_model) {
               $id[]   = $_model['entity_id'];              
           }                 
   $collection = Mage::getModel('marketplace/sellerprofile')->topSeller($id); 
   $count = count($collection);
   if($count>0){
?>
<div class="home_sellers_logo">
    <h2 class="home_pdt_name"><span><?php echo $this->__('Top Sellers'); ?></span></h2>
    <div class="sellers_logo_container">
        <?php
              
        $increment = 1;
        foreach($collection as $_collection){
                    $seller_id  = $_collection['seller_id'];
                    $target_path        = 'marketplace/seller/displayseller/id/' . $seller_id;
                    $mainUrlRewrite     = Mage::getModel('core/url_rewrite')->load($target_path, 'target_path');
                    $getRequestPath     = $mainUrlRewrite->getRequestPath();
                    $get_requestPath    = Mage::getUrl($getRequestPath);
            if($_collection['store_title']!=''){
                    if (strpos($_collection['store_logo'], '.') && $increment<=8) {
                
                ?>
                <a href="<?php echo $get_requestPath; ?>" title="<?php echo $_collection['store_title']; ?>">
                    <img alt="" src="<?php echo Mage::getBaseUrl('media') . "marketplace/resized/" . $_collection['store_logo']; ?>" /> 
                </a>
            <?php          
                 } elseif($increment<=8) {  ?>
                        <a  href="<?php echo $get_requestPath; ?>" title="<?php echo $_collection['store_title']; ?>">
                            <img alt="" src="<?php echo Mage::getBaseUrl('skin') . "frontend/default/market_place/marketplace/images/image.jpg"; ?>"/> 
                           
                        </a> 
           <?php }           
            $increment++;
        }
        }
        ?>
    </div>
</div>
 <?php }
   }  
}     
?>