<?php
/**
*
* @package         Apptha Marketplace
* @version         1.2.1
* @since           Magento 1.5
* @author          Apptha Team
* @copyright       Copyright (C) 2014 Powered by Apptha
* @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
* @Creation Date   Oct 23 2013
* @Modified By     Swathi
* @Modified Date   Apr 07 2014
*
**/
?>

<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<ul class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><span class="addto_wishlist_image"></span><span class="addto_wishlist"><?php echo $this->__('Add to Wishlist') ?></span></a></li>
<?php endif; ?>
<?php
    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
?>
<?php if($_compareUrl) : ?>
    <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><span class="addto_compare_image"></span><span class="addto_compare"><?php echo $this->__('Add to Compare') ?></span></a></li>
<?php endif; ?>
</ul>