<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<div class="price-box" id="product_price">
    <p class="old-price"><?php echo $this->__('Old Price:') ?> <?php echo $this->getPrice() ?></p>
    <p class="special-price"><?php echo $this->getPrice() ?></p>
</div>