<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<?php
/**
 * @deprecated after 1.4.0.1
 */
?>
<?php if ($toplinks && is_array($toplinks)): ?>
    <ul class="links">
        <?php echo $this->getChildHtml() ?>
        <?php foreach ($toplinks as $_toplink): ?>
            <li<?php if ($_toplink['first'] || $_toplink['last']): ?> class="<?php if ($_toplink['first']): ?>first<?php endif; ?><?php if ($_toplink['last']): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_toplink['liParams'] ?>><?php echo $_toplink['beforeText'] ?><a <?php echo $_toplink['aParams'] ?>><?php echo $_toplink['innerText'] ?></a><?php echo $_toplink['afterText'] ?></li>
            <?php endforeach; ?>
    </ul>
<?php endif; ?>
