<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2014
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Apr 1 2014
 *
 * */
?>
<script type="text/javascript">
var myshow;
Event.observe(window, "load", function() {    
window.innerWidth;
	$('myshow1') && $('myshow1').protoShow({
		interval	:	5000,
		captions	: 	true,
                transitionType	: 	"slide",
                navigation      :       false,
                control         :       false
	});
});
</script>
<?php
if(!Mage::helper('marketplace')->checkMarketplaceKey()){
$model = Mage::getModel('catalog/product');//get model product
?>
<!-- get product collection to the selected product type -->
<?php $productCollection = $this->getProductCollections();

$productCount = count($productCollection);?>
<?php if($productCount > 0):?>
<!-- ends here -->
<div class="home_banner">
<!-- Banner Slider Starts -->
<div id="myshow1" class="protoshow">
			<ul class="show">				
			<?php $todayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);
			foreach ($productCollection as $products)
			{
				$product = $model->load($products->getId());
				if (!$product->isGrouped())
				{
					
					$toDate = $product->getspecial_to_date();
					if((!$product->getSpecialPrice())||(($toDate<$todayDate)&&(!empty($toDate))))
					{
						$discount = 0;
					}
					else
					{
						$discountPrice = $product->getPrice() - $product->getSpecialPrice();
						$discount = ($discountPrice * 100) / $product->getPrice();
						$discount = round($discount);
					}
				}
				if(strlen($product->getName())>30)
				{
					$productName = substr($product->getName(),0,30).'...';

				}
				else
				{
					$productName = $product->getName();
				}
				if(strlen($product->getdescription())>170)
				{
					$productDescription = substr($product->getdescription(),0,170).'...';

				}
				else
				{
					$productDescription = $product->getdescription();
				}				
			$splPrice = $product->getSpecialPrice();	
			?>
			<li class="slide" data-slide-interval="">
                            <?php
                            $popularproduct_img = $this->helper('catalog/image')->init($product, 'small_image')
                            ->constrainOnly(TRUE)
                            ->keepAspectRatio(FALSE)
                            ->keepFrame(FALSE)
                            ->resize(613,468); ?>
                            <img src="<?php echo $popularproduct_img; ?>" alt="" />
				<div class="banner">
					<div class="p_name"><?php echo $productName; ?></div>
					<div class="p_des"><?php echo $productDescription; ?></div>                                        
                                        <?php if(!empty($splPrice)) { ?>                    
                                        <span class="price p_spprice">
                                           <del class="p_orprice"><?php echo Mage::helper('core')->currency($product->getPrice(), true, false);?></del>
                                                <?php echo Mage::helper('core')->currency($product->getSpecialPrice(), true, false);?>
                                        </span>
                                        <?php } else  { ?>
                                        <span class="price p_spprice">
                                            <?php echo Mage::helper('core')->currency($product->getPrice(), true, false); ?>
                                        </span>
                                        <?php } ?>
                                        <a href="<?php echo Mage::helper('checkout/cart')->getAddUrl($product); ?>" class="shopnow"><?php echo $this->__('Buy Now'); ?></a>
				</div>
			</li>
			<?php } ?>
		</ul>
	</div>                      
<?php endif; ?>
<!-- Banner Slider Ends -->
<ul class="add_blocks_conatiner">
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('add-blocks')->toHtml() ?>    
</ul>
</div>
<?php } ?>