<?php
/**
* @category Oscp
* @package Oscp_ImageGallery
*/ 
?>

<tr>
    <td class="label"><?php echo $this->getElement()->getLabel() ?><span class="required">*</span></td>
    <td colspan="10" class="value">
     <input id="largeimage" type="file" value="" name="largeimage">
     <?php if($this->getElement()->getValue()): ?>
 <img style="width:40px; height:45px;" 
          src="<?php echo Mage::getBaseUrl('media'). DS.$this->getElement()->getValue();?>" alt="Large Image" title="Large Image" />
<?php endif; ?>
   </td>
</tr>
