<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<?php
//get seller id
$id = $this->getRequest()->getParam('id');
$current_url = Mage::helper('core/url')->getCurrentUrl();
$currentDate = Mage::getModel('core/date')->date('Y-m-d');

//display product collection
$seller_page = Mage::getModel('marketplace/sellerprofile')->collectprofile($id);?>
<?php  $_coreHelper = $this->helper('core');
       $_taxHelper = $this->helper('tax'); ?>
<div id="description-wrapper">
<div class="category-title-description">            
                      
                    
                     
			<div class="title-description">			
                   <div class="page-title category-title">
                        <h1><?php echo $seller_page->getStoreTitle(); ?></h1>
						</div>
				   <div class="category-description std">
				       <p class="mp_profiles_desc"><?php echo $seller_page->getDescription(); ?></p>
                   </div>
                   <div class="category-image">
                   <img src="<?php echo Mage::getBaseUrl('media') . "marketplace/resized/" . $seller_page->getStoreLogo(); ?>" alt="store logo" class="market_place_store_img" />
				   </div>
				   <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
             </div>           
               
                
               

         
         
    <div class="clear"></div>
    <?php  $display_product_count = $this->getCollection();
    $count_product = count($display_product_count);
    if($count_product>0){ ?>
<!-- <h2  class="pdct_name home_pdt_name"><span><?php echo $this->__('All Products'); ?></span> -->
    <?php } //Display seller category and products   ?>
    <div class="toolbar">
<?php
$cat_ids_value          = array();
$display_cat_product    = $this->getRequest()->getParam('category_name');
$sort_product           = $this->getRequest()->getParam('sorting');
$seller_value           = $this->sellerproduct($id);
foreach ($seller_value as $_value) {
    if (!in_array($_value['category_id'], $cat_ids_value)) {
        $cat_ids_value[] = $_value['category_id'];
    }
}
echo $this->getPagerHtml();
?>
        <div class="sorter">
            <form name="category_products" id="mp_category_products" action="" method="post"> 
			<div class="sort-by">
		    <label><?php echo $this->__('List By') ?></label>
                <select name="sorting" onchange="this.form.submit();" id="sorting">
                    <option value="name?dir=asc" <?php if ($sort_product == 'name?dir=asc') { ?>selected="selected" <?php } ?>><?php echo $this->__('A-Z'); ?></option>
                    
					<option value="price?dir=asc" <?php if ($sort_product == 'price?dir=asc') { ?>selected="selected" <?php } ?>><?php echo $this->__('Price low'); ?></option>

                    <option value="price?dir=desc" <?php if ($sort_product == 'price?dir=desc') { ?>selected="selected" <?php } ?>><?php echo $this->__('Price high'); ?></option>

                    <option value="position?dir=asc" <?php if ($sort_product == 'position?dir=asc') { ?>selected="selected" <?php } ?>><?php echo $this->__('Position'); ?></option>
                </select>
				</div>
            </form>
        </div></div> 

    </h2>
	
    <ul class="products-grid product_snipt f-left">
       
        <?php

        $display_product1 = $this->getCollection();
		//echo $display_product1->getSelect()->__toString();

        $display_product = $this->getCollection();

        if (!empty($display_product)) {
            foreach ($display_product as $_product) {
                $wordsCount_category = strlen($_product->getName()); ?>                
                <li class="item">
				<div class="productbg">
						<?php if ($_product->getNews_from_date()): ?>
						<?php if ($_product->getNews_to_date()): ?>
							<span class="new">
								<img src="<?php echo $this->getskinUrl('images/new.png') ?>" width="82" height="72" alt=""/>
							</span>
						<?php endif; ?>
					   <?php endif; ?>
					   <?php if ($_product->getSpecialPrice()): ?>
					     <span class="sale">
                                    <img src="<?php echo $this->getskinUrl('images/sale.png') ?>" width="82" height="72" alt=""/>
                                </span>
					   <?php endif ?>
                    <a href="<?php echo $_product->getProductUrl(); ?>">
                        <img class="product-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(183); ?>" width="183" height="183" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
					<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
					<?php $_productName = $this->escapeHtml($_product->getName());?>
                                       <?php $_count = strlen($_productName);?>
                                        <?php echo strip_tags(substr($_productName, 0, 80));?>
                                        <?php if ($_count > 80): ?>
                                           <?php echo $this->__('...')?>  
										   <?php endif; ?>
                                        </a></h2>
										<div class="product-secondary">
                        <?php //if($_product->isSaleable() && !$_product->canConfigure()): ?>
                            <p class="action"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                        <?php //elseif($_product->isSaleable()): ?>
                            <p class="action"><a title="<?php echo $this->__('View Details') ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                        
                        <?php //endif; ?>
                        <ul class="add-to-links">
                            <?php //if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php //endif; ?>
                            <?php //if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $this->getAddToCompareUrl($_product) ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php //endif; ?>
                        </ul>
                    </div>
                    <div class="price-Or-retailername">
                            <?php
                            //Display Product Price
                            $price          = $_product->getPrice();
                            $spl_price      = $_product->getSpecialPrice();
                            $dealExpireDate = $_product->getspecial_to_date(); ?>  
					   

								<div class="sale-price">
								<?php if ($_product->getSpecialPrice()): ?>
									<div class="now">
                                        <span class="price"><?php                                            
                                            $_price = $_taxHelper->getPrice($_product, $_product->getFinalPrice());
                                            echo $_coreHelper->currency($_price, true, false);
                                            ?>
                                        </span>
                                    </div>
                                    <div class="was">
                                        <label><?php echo $this->__('was'); ?></label>
                                        <span class="price"><?php
                                            
                                            $_realPrice = $_taxHelper->getPrice($_product, $_product->getPrice());
                                            echo $_coreHelper->currency($_realPrice, true, false);
                                            ?>
                                        </span>
                                    </div>
								<?php else:?>
								 <p> <?php echo Mage::helper('core')->currency($price, true, false); ?></p>
								<?php endif ?>
								</div>
							
							<div class="retailer-name">
								<?php									
									$_product_id = $_product->getEntityId();
									$retailerStoreName = Mage::helper('addcustomerattribute')->getRetailerStoreName($_product_id);
									$retailerStoreLink = Mage::helper('addcustomerattribute')->getRetailerStoreLink($_product_id);
								?>	
								<a href='<?php echo $retailerStoreLink; ?>' class="link_seller"><?php echo $retailerStoreName ?></a>
								<!-- <a href="#"><?php echo $this->__('Retailer Name Link') ?></a> -->
							</div>
							<div style="clear: both; height: 0;">&nbsp;</div>
					   </div>
                </li>
                        <?php   }
                    } else {
                        echo 'No products exists';
                    }    ?>
   </ul>
</div>
</div>
