<?php //BOF developer-19 24/06/2013     ?>
<?php // developer-19 display leftcategory for marketplace    ?>
<?php $_collection = $this->getRetailer(); ?>
<div class="left-category">
    <div class="block-title"><h2><?php echo $this->__('Retailers') ?></h2></div>
    <ul id="left-nav">
        <?php foreach ($_collection as $_retailer): ?>
            <?php
            $_targetPath = 'marketplace/seller/displayseller/id/' . $_retailer->getSellerId();
            $_mainUrlRewrite = Mage::helper('marketplace')->getTargetPlace($_targetPath);
            $_getRequestPath = $_mainUrlRewrite->getRequestPath();
            $_getUrl = Mage::getUrl($_getRequestPath);
            ?>
            <?php $_image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'marketplace/resized/' . $_retailer->getStoreLogo() ?>	
            <li class="Category ">
                <a href="<?php echo $_getUrl ?>"><?php echo $_title = $_retailer->getStoreTitle(); ?></a>
            </li> 
			<?php //endif; ?>
        <?php endforeach; ?>
    </ul>
	<script type="text/javascript">
        jQuery(document).ready(function() {
            //jQuery('#nav').find('ul').hide(); 
            jQuery('#left-nav').find('li.parent > a ').after('<span class="opener"></span>');
            jQuery('#left-nav').find('li.active.parent').addClass('open');
            jQuery('#left-nav li.active.parent').find(' > ul').show();
            jQuery('.opener').click(function() {
                jQuery('#left-nav').find('a').removeClass('clicked');
                jQuery('#left-nav').find('a').addClass('unclicked');
                jQuery(this).parent().find('> a').removeClass('unclicked');
                jQuery(this).parent().find('> a').addClass('clicked');

                if (jQuery(this).parent().hasClass('active')) {
                    jQuery(this).parent().removeClass('active');
                    jQuery(this).parent().find('ul').hide();
                } else {
                    jQuery(this).parent().parent().find('li.parent').removeClass('active');
                    jQuery(this).parent().parent().find('ul').hide();
                    jQuery(this).parent().addClass('active');
                    jQuery(this).parent().find(' > ul').show();
                }
                ;
            });

        });
    </script>
</div>
<?php //EOF developer-19 24/06/2013   ?>
