<?php $_collection = $this->getRetailer();?>
<div class="left-category">
       <h2><?php echo $this->__('Retailers')?></h2>
	   <ul id="left-nav">
<?php foreach($_collection as $_retailer):?>
	<?php 
	        $_targetPath = 'marketplace/seller/displayseller/id/' . $_retailer->getSellerId();
            $_mainUrlRewrite     = Mage::helper('marketplace')->getTargetPlace($_targetPath);
            $_getRequestPath     = $_mainUrlRewrite->getRequestPath();
            $_getUrl  = Mage::getUrl($_getRequestPath);
	?>
	<?php $_image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'marketplace/resized/'.$_retailer->getStoreLogo() ?>	
		<li class="Category">
            <a href="<?php echo $_getUrl?>"><?php echo $_title = $_retailer->getStoreTitle();?></a>
		</li>               
<?php endforeach;?>
        </ul>
</div>





