<?php
/**
 * Oscp.com
 *
 * Oscp Shippicker Module 
 *
 * @category     Magento Extension
 * @copyright    Copyright (c) 2011 Ecommerce Team (http://www.ecommerce-team.com)
 * @author       Ecommerce Team
 * @version      1.0
 */ ?>
 <tr>
      <th colspan="2" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
         <?php
			$block = $this->getLayout()->createBlock('checkout/cart_shipping');
			$block->setTemplate('shippicker/checkout/total/shipping/shippicker.phtml');
			echo $block->_toHtml(); 
    	 ?>
      </th>
 </tr>
