<?php //BOF developer-19 2/6/2013   ?>
<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
            <h3><?php //echo $post->getCreatedTime();   ?></h3>
        </div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>
        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
        <div class="postDetails">           
            <?php echo Mage::helper('blog')->__('Posted on'); ?> <?php echo $post->getCreatedTime(); ?><br/><?php echo $this->__('by') ?> <?php echo $post->getUser(); ?>
        </div>
        <?php if ($this->getCommentsEnabled()): ?>
            <div class="comment">
                <?php echo $this->__('There have been') ?> <?php echo $post->getCommentCount(); ?><?php echo $this->__('Comments') ?>
            </div>
        <?php endif; ?>
        <div class="posted-tag">
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <?php echo $this->__('This post was posted in') ?>
                <?php foreach ($postCats as $data): ?>
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                <?php endforeach; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endforeach; ?>
<?php //EOF developer-19 2/6/2013 ?>
