<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php $i=0; foreach ($posts as $post): ?>
    <?php if($i==1) break; ?>
	<div class="block-title">
        <strong><span><?php echo $this->__('Remade Blog'); ?></span></strong>
		<h3><?php echo Mage::helper('blog')->__('Posted on'); ?> <?php echo $post->getCreatedTime(); ?><br/><?php echo $this->__('by')?> <?php echo $post->getUser(); ?></h3>
    </div>
    <div class="postWrapper">
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>           
        </div>
        <div class="postContent"><?php //echo $post->getPostContent(); ?><?php
                                $_postName = $post->getPostContent();
                                        $_count = strlen($_postName);
                                        echo strip_tags(substr($_postName, 0, 680));
                                        if ($_count > 680) {
                                            echo '...';
                                        }
                                        ?><div class="read"><a class="expand" href="javascript:void(0)">Read more</a></div></div>

        <?php echo $this->getBookmarkHtml($post) ?>
        <div class="tags"><?php echo $this->getTagsHtml($post) ?></div>
    </div>
	<?php $i++;?>
<?php endforeach; ?>
<script type="text/javascript">
jQuery('.expand').click(function(){
	if(jQuery(this).parent().hasClass("less")){
	jQuery('.postContent').toggleClass('expanddiv');
	jQuery('.expand').html("Read more");
	jQuery(this).parent().toggleClass("less");
	}
	else{
	jQuery('.postContent').toggleClass('expanddiv');
	jQuery('.expand').html("Read less");
	jQuery(this).parent().toggleClass("less");
	}

});
</script>