<div class="links">
    <div class="collapsible mobile-collapsible">
	<div class="block-title account"><div class="menu-recent"><h5><?php echo Mage::helper('blog')->__('Recent Posts/Tags'); ?></h5></div></div>
	<div class="block-content">
        <?php if ($posts = $this->getRecent()): ?>
            <div class="menu-recent">
                <h5><?php echo Mage::helper('blog')->__('Recent Posts'); ?></h5>
                <ul>
                    <?php foreach ($posts as $post): ?>
                        <li><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
						 <h3><?php echo $post->getCreatedTime(); ?></h3></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if ($this->getCategories()->count() && Mage::getStoreConfig('blog/menu/category')): ?>
            <div class="menu-categories">
                <h5><?php echo Mage::helper('blog')->__('Tags'); ?></h5>
                <ul>
                    <?php $cats = $this->getCategories(); ?>
                    <?php foreach ($cats as $cat): ?>
                        <li><a href="<?php echo $cat->getAddress(); ?>" ><?php echo $cat->getTitle(); ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>
        <?php echo $this->getChildHtml('blog_tags'); ?>
    </div>
</div>
</div>