<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<form action="<?php echo $this->getAdminMailActionUrll(); ?>" id="marketplaceContactForm" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('marketplace')->__('Contact Information') ?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="subject" class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Subject') ?></label>
                    <div class="input-box">
                        <input name="subject" id="subject" title="<?php echo Mage::helper('marketplace')->__('Subject') ?>" value="" class="input-text required-entry" type="text" />
                    </div>
                </div>

            </li> 
            <li class="wide">
                <label for="message" class="required"><em>*</em><?php echo Mage::helper('marketplace')->__('Message') ?></label>
                <div class="input-box">
                    <textarea name="message" id="message" title="<?php echo Mage::helper('marketplace')->__('Message') ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('marketplace')->__('* Required Fields') ?></p> 
        <button type="submit" title="<?php echo Mage::helper('marketplace')->__('Submit') ?>" class="button"><span><span><?php echo Mage::helper('marketplace')->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var marketplaceContactForm = new VarienForm('marketplaceContactForm', true);
    //]]>
</script>