<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<?php
// Initilize payment code and description
$_code = $this->getMethodCode();
$description = Mage::helper('paypaladaptive')->getPaymentDescription();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">    
    <?php if (!empty($description)) {  // If checking whether description available or not   ?>
        <li> <?php echo $description; ?> </li>    
<?php } // End if for checking whether description available or not   ?> 
    <li><?php echo $this->__('You will be redirected to the Paypal Checkout website when you place an order.') ?></li>
</ul>