<?php //BOF developer-19 08/02/2013   ?>
<div class="contact">
    <div class="email-info">
	<?php $_storeEmailAddress = Mage::getStoreConfig('trans_email/ident_general/email'); ?>
        <a href="mailto:<?php echo $_storeEmailAddress; ?>"><?php echo $_storeEmailAddress; ?></a>
			
            <?php //EOF Developer.19 for get email from admin store information ?>
    </div>
</div>
<?php
//EOF developer-19 08/02/2013 ?>