<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<?php //BOF developer-19 10/06/2013 ?>
<div class="form-add">
    <h2 class="home_pdt_name"><span><?php echo $this->__('Write Your Own Review') ?></span></h2>
    <?php if ($this->getAllowWriteReviewFlag()): ?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="review-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <fieldset>
            <?php echo $this->getChildHtml('form_fields_before')?>
            <h3><?php echo $this->__("You are reviewing:"); ?> <span><?php echo $this->escapeHtml($this->getProductInfo()->getName()) ?></span></h3>
            <?php if( $this->getRatings() && $this->getRatings()->getSize()): ?>
                <h5><?php echo $this->__('How do you rate this product?') ?> <em class="required">*</em></h5>
                <span id="input-message-box"></span>
                <table class="data-table" id="product-review-table">
                    <tbody>
                    <?php foreach ($this->getRatings() as $_rating): ?>
                        <tr>                           
							 <td class="value">
								<div class="label"><?php echo $this->escapeHtml($_rating->getRatingCode()) ?></div>
								 <?php foreach ($_rating->getOptions() as $_option): ?>
									<div id="radio_upper_<?php echo $_option->getValue() ?>" class="upper-redio requuired-entry">
										<input type="radio" name="ratings[<?php echo $_rating->getId() ?>]" id="<?php echo $this->escapeHtml($_rating->getRatingCode()) ?>_<?php echo $_option->getValue() ?>" value="<?php echo $_option->getId() ?>" class="radio" />
									</div>
								<?php endforeach; ?>
							</td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                <script type="text/javascript">decorateTable('product-review-table')</script>
            <?php endif; ?>
                <ul class="form-list f-left product-detail-review-form">
                    <li>
                        <label for="nickname_field" class="required"><em>*</em><?php echo $this->__('Nickname') ?></label>
                        <div class="input-box">
                            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getNickname()) ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="summary_field" class="required"><em>*</em><?php echo $this->__('Summary of Your Review') ?></label>
                        <div class="input-box">
                            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="<?php echo $this->escapeHtml($data->getTitle()) ?>" />
                        </div>
                    </li>
                </ul>
                <ul class="form-list f-left product-detail-review-area">
                    <li>
                        <label for="review_field" class="required"><em>*</em><?php echo $this->__('Review') ?></label>
                        <div class="input-box">
                            <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"><?php echo $this->escapeHtml($data->getDetail()) ?></textarea>
                        </div>
						<p class="required"><?php echo $this->__('*All fields are required') ?></p>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="<?php echo $this->__('Submit Review') ?>" class="button"><span><span><?php echo $this->__('Submit Review') ?></span></span></button>
            </div>
    </form>
	<?php //EOF developer-19 10/06/2013 ?>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', '<?php echo $this->__('Please select one of each of the ratings above') ?>', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;

                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');

                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }

                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
	<script type="text/javascript">
	
		jQuery(document).ready(function(){
			
			jQuery('#radio_upper_1').click(function(){
				jQuery('#product-review-table .value > div').removeClass('active');
				jQuery('#radio_upper_1').addClass('active');
			});

			jQuery('#radio_upper_2').click(function(){
				 jQuery('#product-review-table .value > div').removeClass('active');
				 jQuery('#radio_upper_1').addClass('active');
				 jQuery('#radio_upper_2').addClass('active');
			});
			jQuery('#radio_upper_3').click(function(){
				jQuery('#product-review-table .value > div').removeClass('active');
				jQuery('#radio_upper_1').addClass('active');
				jQuery('#radio_upper_2').addClass('active');
				jQuery('#radio_upper_3').addClass('active');
			});

			jQuery('#radio_upper_4').click(function(){
				 jQuery('#product-review-table .value > div').removeClass('active');
				 jQuery('#radio_upper_1').addClass('active');
				 jQuery('#radio_upper_2').addClass('active');
				 jQuery('#radio_upper_3').addClass('active');
				 jQuery('#radio_upper_4').addClass('active');
			});

			jQuery('#radio_upper_5').click(function(){
				 jQuery('#radio_upper_1').addClass('active');
				 jQuery('#radio_upper_2').addClass('active');
				 jQuery('#radio_upper_3').addClass('active');
				 jQuery('#radio_upper_4').addClass('active');
				 jQuery('#radio_upper_5').addClass('active');
			});
		});
        </script>      <?php else: ?>
    <p class="review-nologged" id="review-form">
        <?php echo $this->__('Only registered users can write reviews. Please, <a href="%s">log in</a> or <a href="%s">register</a>', $this->getLoginLink(), Mage::helper('customer')->getRegisterUrl()) ?>
    </p>
    <?php endif ?>
</div>
