<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Jenifer Ratchanya
 * @Modified Date   Mar 27 2014
 *
 * */
?>
<div class="box-collateral box-tags">
    <h2 class="home_pdt_name"><span><?php echo $this->__('Product Tags') ?></span></h2>
    <?php echo $this->getChildHtml('list_before') ?>
    <?php if ($this->getCount()): ?>
        <h3><?php echo $this->__('Other people marked this product with these tags:') ?></h3>
        <ul id="<?php echo $this->getUniqueHtmlId('product-tags_'); ?>" class="product-tags">
            <?php echo $this->renderTags('<li><a href="%1$s">%2$s</a> (%3$s)</li>') ?>
        </ul>
        <script type="text/javascript">
            decorateGeneric($("<?php echo $this->getUniqueHtmlId('product-tags_'); ?>").select('li'), ['first', 'last']);
        </script>
    <?php endif; ?>
    <form id="addTagForm" action="<?php echo $this->getFormAction(); ?>" method="get">
        <div class="form-add">
            <label for="productTagName"><?php echo $this->__('Add Your Tags:') ?></label>
            <div class="input-box">
                <input type="text" class="input-text required-entry" name="productTagName" id="productTagName" />
            </div>
            <button type="button" title="<?php echo $this->__('Add Tags') ?>" class="button" onclick="submitTagForm()">
                <span>
                    <span><?php echo $this->__('Add Tags') ?></span>
                </span>
            </button>
        </div>
    </form>
    <p class="note"><?php echo $this->__("Use spaces to separate tags. Use single quotes (') for phrases.") ?></p>
    <script type="text/javascript">
        //<![CDATA[
        var addTagFormJs = new VarienForm('addTagForm');
        function submitTagForm() {
           var enableSocialLogin = parseInt("<?php echo Mage::getStoreConfig('sociallogin/general/enable_sociallogin'); ?>");
           var customerLogged = parseInt("<?php echo Mage::getSingleton('customer/session')->isLoggedIn(); ?>");            
           if(customerLogged!==1 && enableSocialLogin==1){              
                 javascript:apptha_sociallogin();
                } else {                  
            if (addTagFormJs.validator.validate()) {                 
                    addTagFormJs.form.submit();
                }  
            }
        }
        //]]>
    </script>
</div>
