<?php
/**
 *
 * @package         Apptha Marketplace
 * @version         1.2.1
 * @since           Magento 1.5
 * @author          Apptha Team
 * @copyright       Copyright (C) 2014 Powered by Apptha
 * @license         http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @Creation Date   Oct 23 2012
 * @Modified By     Swathi
 * @Modified Date   Apr 07 2014
 *
 * */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <?php echo $this->getBlockHtml('formkey') ?>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>
        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>  
            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getChildHtml('extrahint') ?>
            <?php echo $this->getChildHtml('alert_urls') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>
            <?php echo $this->getTierPriceHtml() ?> 
            <?php $_product = $this->getProduct(); ?>
            <?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
            <div class="product_sellers_cart">
            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>                   
                <ul class="add-to-links">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><span class="addto_wishlist_image"></span><span class="addto_wishlist"><?php echo $this->__('Add to Wishlist'); ?></span></a></li>
                <?php endif; ?>
                    <li class="separator">|</li>
                <?php
                    $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product);
                ?>
                <?php if($_compareUrl) : ?>
                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><span class="addto_compare_image"></span><span class="addto_compare"><?php echo $this->__('Add to Compare'); ?></span></a></li>
                <?php endif; ?>
                </ul> 
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>  
                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
            </div>            
            <div class="sellers_social_share">                
            <script type="text/javascript">(function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id))
                    return;
                js = d.createElement(s);
                js.id = id;
                js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=439794342797425";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
            </script>
             <div id="fb-root"></div>
            <?php                
                $fbUrl = 'http://www.facebook.com/sharer.php?s=100' . '&p[url]=' . $_product->getProductUrl(). '&p[images][0]=' . $_product->getImageUrl() . '&p[title]=' . $_product->getName() . '&p[summary]=' . strip_tags($_product->getShortDescription());
            ?>            
            <div class="product_sellers_share f-left">
                <?php // Facebook share ?>
               <div class="fb-like f-left mp_fb_like_btn" data-href="<?php echo $fbUrl; ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="false"></div>
               <?php //Twitter Share ?>                
                <a href="https://twitter.com/share" class="twitter-share-button f-left mp_tweet_btn" style="width:50px">Tweet</a>
                <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                
                 <?php //Google Share Button
                $googleImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN) . 'frontend/default/market_place/marketplace/images/gplus.png';
                ?>
                    <a href="https://plus.google.com/share?url=<?php echo $_product->getProductUrl(); ?>" class="mp_google_btn" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');
                        return false;" title="<?php echo $this->__('Share with Google+'); ?>">
                        <img src="<?php echo $googleImage; ?>" class="f-left" alt="<?php echo $this->__('Share with Google+'); ?>" />
                    </a> 
              </div>            
            <div class="product_sellers_email f-left">  
                <?php if ($this->canEmailToFriend()): ?>
                <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to your Friend') ?></a></p>
            <?php endif; ?>
             </div>
        </div>
            <?php echo $this->getChildHtml('other');?>
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
        </div>
        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>         
        <div class="clearer"></div>        
    </form>
        <div class="mrkt_plc_tab">
            <?php echo $this->getChildHtml('info_tabs');?>
        </div>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>    
<?php if($this->getChildGroup('detailed_info', 'getChildHtml')){ ?>
<div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
    </div>
<?php } ?>
<?php if($this->getChildHtml('upsell_products')){ ?>
<div class="product-collateral">
        <?php echo $this->getChildHtml('upsell_products') ?>
</div>
<?php } ?>
    <?php if($this->getChildHtml('product_additional_data')){ ?>
<div class="product-collateral">
        <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
    <?php } ?>
</div>